- custom_components/HomeWhiz/__init__.py
- custom_components/HomeWhiz/config_flow.py
- custom_components/HomeWhiz/homewhiz.py
- custom_components/HomeWhiz/manifest.json
- custom_components/HomeWhiz/strings.json
- custom_components/HomeWhiz/translations/en.json
To not have an empty modal, i added some translation/strings. 
It´s not much now, but you´ll get some info.
> Added some translation and changed BleakScanner recieval

- custom_components/HomeWhiz/translations/de.json
Adds German translation to HomeWhiz component
> Add German translation

- custom_components/homewhiz/__init__.py
- custom_components/homewhiz/homewhiz.py
- custom_components/homewhiz/sensor.py
This will add some more logging commands to help identify unknown states.
> Add more logging

- .github/workflows/hacs.yml
- .github/workflows/hassfest.yml
- custom_components/homewhiz/manifest.json
- custom_components/homewhiz/strings.json
- custom_components/homewhiz/translations/bg.json
- custom_components/homewhiz/translations/de.json
- custom_components/homewhiz/translations/en.json
- custom_components/homewhiz/translations/es.json
- custom_components/homewhiz/translations/nl.json
- custom_components/homewhiz/translations/tr.json
- hacs.json
This is [required for repositories](https://hacs.xyz/docs/publish/include/#before-submitting) in order to be added to the HACS default list.
> Add github actions for validation

- .github/workflows/black.yml
- custom_components/homewhiz/__init__.py
- custom_components/homewhiz/homewhiz.py
Validates black formatting via Github action. Also includes removal of unused import and small refactoring (thanks to pylint).
> Validate black formatting via Github action

- custom_components/homewhiz/__init__.py
Removed the MAC address from every log, as in reality it's not useful at all
> Don't try to reconnect disconnected coordinator

- custom_components/homewhiz/__init__.py
- custom_components/homewhiz/api.py
- custom_components/homewhiz/config_flow.py
- custom_components/homewhiz/homewhiz.py
- custom_components/homewhiz/sensor.py
> Fetch user appliance description from the API

- .github/workflows/pre-commit_ci.yml
- .pre-commit-config.yaml
- custom_components/homewhiz/api.py
- custom_components/homewhiz/appliance_config.py
- custom_components/homewhiz/config_flow.py
- custom_components/homewhiz/sensor.py
- custom_components/homewhiz/tests/test_config.py
- custom_components/homewhiz/tests/test_sensor.py
- linux_dev.md
- requirements_dev.txt
- scripts/generate_translations.py
Inspired by pre-commit configuration from homeassistant core project.
> Add pre-commit configuration

- custom_components/homewhiz/appliance_config.py
- custom_components/homewhiz/tests/fixtures/example_ac_config.json
- custom_components/homewhiz/tests/test_config.py
Added all the possible fields
Inspired by the original app code
Not used yet, but can be used for creating new entities
> Complete the ApplianceConfiguration model

- custom_components/homewhiz/__init__.py
- custom_components/homewhiz/cloud.py
- custom_components/homewhiz/manifest.json
> Install awsiotsdk lazily

- README.md
> Add section for retrieving logs to readme

- custom_components/homewhiz/__init__.py
- custom_components/homewhiz/api.py
- custom_components/homewhiz/cloud.py
Heavily inspired by https://github.com/dahlb/ha_hatch/blob/a838a755a84df47de148db767b839693e04726f2/custom_components/ha_hatch/__init__.py#L129
> Reconnect to the cloud when credentials expire

- custom_components/homewhiz/appliance_config.py
- custom_components/homewhiz/cloud.py
- custom_components/homewhiz/const.py
- custom_components/homewhiz/homewhiz.py
- custom_components/homewhiz/select.py
> Draft: Send cloud commands

- custom_components/homewhiz/cloud.py
> Fix non Tuya cloud connection

- custom_components/homewhiz/__init__.py
- custom_components/homewhiz/appliance_controls.py
- custom_components/homewhiz/climate.py
- custom_components/homewhiz/cloud.py
- custom_components/homewhiz/tests/test_ac.py
- custom_components/homewhiz/tests/test_advanced_ac.py
- custom_components/homewhiz/tests/test_dishwasher.py
> Handle advanced AC features

- custom_components/homewhiz/bluetooth.py
I hope that this might help to identify the issue in #94.
> More debug logging for Bluetooth

- custom_components/homewhiz/climate.py
> Add kwargs to async_set_temperature

- custom_components/homewhiz/api.py
Allow null applianceSerialNumber
> Update api.py - Allow null applianceSerialNumber

- custom_components/homewhiz/bluetooth.py
> Fix bleak rssi deprecation warning

- custom_components/homewhiz/translations/pl.json
Fixed typos and filled in the generic fields
> Fix the Polish translation

- custom_components/homewhiz/translations/ru.json
- scripts/generate_translations.py
Closes #141 
@carawan Could you maybe test this translation file and provide feedback?
> Add russian translation

- .pre-commit-config.yaml
- custom_components/homewhiz/climate.py
- custom_components/homewhiz/translations/pt.json
- Update pre-commit hooks
- Run pre-commit
- Use Python 3.11 for pyupgrade instead of Python 3.10
> Update and fix pre-commit

- .github/workflows/pre-commit_ci.yml
- custom_components/homewhiz/translations/hu.json
Continue from https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/pull/166
> Hungarian translation

- .github/workflows/pre-commit_ci.yml
- custom_components/homewhiz/translations/hu.json
- scripts/base_translations/sk.json
Continue from https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/pull/164
> Slovakian Translation 

- custom_components/homewhiz/translations/it.json
> Adjust some Italien translations and remove weird letters

- custom_components/homewhiz/translations/sk.json
- scripts/generate_translations.py
Adds Slovakian translation and handle calculated washer delay in translations.
@misa1515 Please have a look 😄
> 198 Slovakian translation

- custom_components/homewhiz/appliance_config.py
Allows setting up tea machines, thanks to @sarpdoruk.
> Make RecipeFormatVersion optional for tea maker

- custom_components/homewhiz/__init__.py
Fixes #210 by reverting 26bdab3
> Fix awsiotsdk dependency on ARM

- README.md
> Add extraction fan and update README

- custom_components/homewhiz/__init__.py
- custom_components/homewhiz/cloud.py
I saw errors during response validation when a washing machine via cloud was connected to Home assistant.
> 207 Washing Machine via Cloud does not retrieve values (unavailable)

- custom_components/homewhiz/translations/pl.json
Add translations required for washer Grundig GW5P58415WBPB and dryer Grundig GT76824WBPB.
> Add new translations for washer and dryer

- .github/workflows/check_version.yml
- custom_components/homewhiz/manifest.json
- Add Github action to ensure version in tag matches manifest.json version
- Update version
> 239 version inconsistency

- README.md
- custom_components/homewhiz/const.py
- custom_components/homewhiz/icons.json
This closes #140 and implements icon translations.
Hopefully, this will motivate users to contribute, similar to normal translations.
> 140 entity icons not working

- .devcontainer/devcontainer.json
- .flake8
- .pre-commit-config.yaml
- custom_components/homewhiz/__init__.py
- custom_components/homewhiz/binary_sensor.py
- custom_components/homewhiz/climate.py
- custom_components/homewhiz/entity.py
- custom_components/homewhiz/homewhiz.py
- custom_components/homewhiz/select.py
- custom_components/homewhiz/sensor.py
- custom_components/homewhiz/switch.py
- scripts/generate_translations.py
- Add configuration for GitHub codespace
- Update pre-commit hooks
- Use Ruff instead of black, etc.
> Add Codespace confg, update pre-commit and switch to Ruff

- custom_components/homewhiz/translations/de.json
Fixes and improves some translation for German.
> Update German translation

- custom_components/homewhiz/__init__.py
- custom_components/homewhiz/bluetooth.py
- custom_components/homewhiz/config_flow.py
- custom_components/homewhiz/const.py
- custom_components/homewhiz/entity.py
- custom_components/homewhiz/translations/en.json
Fixes #242 
Introduces a reconnection logic by time interval for Bluetooth which can be controlled via device options.
Updates the reconnection flow for Bluetooth.
> Update Bluetooth reconnection flow and introduce reconnection by time interval

- custom_components/homewhiz/appliance_controls.py
> Avoid bidict duplication error
